# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dat-hub'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      MS_SQL_PASS=C@maimssqlser2022
      MS_SQL_CONN='server=mssqldb;uid=sa;password=C@maimssqlser2022;database=CamAIDatabase;TrustServerCertificate=true'
      STAGE=Development
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker compose push'
    
- task: SSH@0
  displayName: "connecting to ssh-server"
  inputs:
    sshEndpoint: 'ssh-server'
    runOptions: 'inline'
    readyTimeout: '20000'
    inline: ls