# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Docker build and publish'
  inputs:
    containerRegistry: 'dat-hub'
    repository: 'ryuuji2232/test-camai-hub'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: './CamAISolution'
    tags: camai-web-api
- task: SSH@0
  displayName: "connecting to ssh-server"
  inputs:
    sshEndpoint: 'ssh-server'
    runOptions: 'inline'
    readyTimeout: '20000'
    inline: ls