version: '3.9'
services:
  web-api:
    build:
      context: ./CamAISolution
      dockerfile: Host.CamAI.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
