#Docker compose for VPS

version: '3.9'
services:
  mssqldb:
    restart: always
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MS_SQL_PASS}
    ports:
      - "1434:1433"
    volumes:
      - data:/var/opt/mssql/data
  web-api:
    image: milease/camai-backend:camai-web-api
    ports:
      - "8090:8080"
      - "8091:8081"
    environment:
      - ConnectionStrings__Default=${MS_SQL_CONN}
      - GoogleSecret__PrivateKey=${GOOGLE_SERVICE_PRIVATE_KEY}
      - RabbitMq__HostName=${RABBITMQ_HOST}
      - RabbitMq__Username=${RABBITMQ_USER}
      - RabbitMq__Password=${RABBITMQ_PASS}
      - RabbitMq__Port=${RABBITMQ_PORT}
      - ASPNETCORE_ENVIRONMENT=${STAGE}
    depends_on:
      - mssqldb
  camai-rabbitmq:
    image: rabbitmq:3.12.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
    volumes:
      - camai-rabbitmq-lib:/var/camai/lib/rabbitmq/
      - camai-rabbitmq-log:/var/camai/log/rabbitmq/
volumes:
  data:
  camai-rabbitmq-lib:
  camai-rabbitmq-log: